[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

# Redirigir las llamadas /api a las Netlify Functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Redirigir todo lo demás a index.html (para que funcione el React Router)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200